### ISSUE TITLE
Error while using node-sdk with next.js application

### ISSUE THREAD

**Issue by trace2798** [hellosign/hellosign-openapi#310]
Hey I am trying to test it for the first time with a Next.js application and got the following 

```
- error ./node_modules/@dropbox/sign/dist/api.js
Module not found: Can't resolve './aes'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./lib/dropbox.ts
./app/page.tsx
```
The steps I took after initiating my next.js application:
1. npm install @dropbox/sign
2. Try the [accountGet()](https://github.com/hellosign/dropbox-sign-node/blob/HEAD/docs/api/AccountApi.md#accountget) example

**Comment by imonkia** [comment]
@trace2798

The reason you are seeing that error is because the Dropbox Sign API uses Node.js specific modules, or modules that are not available on the client side.

You can address that issue by looking into NextJS' `getStaticProps`, `getStaticPaths` or `getServerSideProps` functions.

References:
* [Module Not Found](https://nextjs.org/docs/messages/module-not-found)
* [Get Server Side Props](https://nextjs.org/docs/pages/building-your-application/data-fetching/get-server-side-props)
* [Get Static Paths](https://nextjs.org/docs/pages/building-your-application/data-fetching/get-static-paths)
* [Get Static Props](https://nextjs.org/docs/pages/building-your-application/data-fetching/get-static-props)

**Comment by trace2798** [comment]
@imonkia So basically it does not support next.js app directory?
